export type Product = {
  id: string;
  name: string;
  category: "Cervezas" | "Bebidas" | "Cocina";
  description: string;
  image?: string;
  tag: string;
  note: string;
  group: string;
  attributes: string[];
  allergens: string[];
  beerStyle?: string;
  relatedIds: string[];
  price: number;
  nutrition: {
    basis: string;
    calories: string;
    fats: string;
    proteins: string;
    carbs: string;
    sugars: string;
  };
  beerProfile?: {
    style: string;
    descriptors: string[];
    ibu: string;
    abv: string;
    srm: string;
  };
  servings?: { label: string; volume: string; price: number }[];
  eventoMenu?: boolean;
};

export type MenuSettings = {
  foodGroups: string[];
  foodPreferences: string[];
  allergenOptions: string[];
  drinkGroups: string[];
  beerStyles: string[];
};

export type AppSettings = {
  businessName: string;
  brandTagline: string;
  logoUrl: string;
  heroImageUrl: string;
  accentColor: string;
  heroEyebrow: string;
  heroTitle: string;
  heroHighlight: string;
  heroDescription: string;
  contactEmail: string;
  phone: string;
  currency: "ARS" | "USD" | "BRL";
  defaultLanguage: string;
  orderNotifications: boolean;
  serviceNotifications: boolean;
  weeklySummary: boolean;
  orderToken: string;
  eventModeActive: boolean;
  hours?: string;
};

export const MENU_PRODUCTS_STORAGE_KEY = "restaurant-template-products-v1";
export const MENU_SETTINGS_STORAGE_KEY = "restaurant-template-menu-settings-v1";
export const ADMIN_APP_SETTINGS_KEY = "restaurant-template-app-settings-v1";

export const DEFAULT_APP_SETTINGS: AppSettings = {
  businessName: "23 Ríos",
  brandTagline: "Cervecería artesanal",
  logoUrl: "/images/23rios/logo_23_negro-removebg-preview.png",
  heroImageUrl: "/images/23rios/canillas.png",
  accentColor: "#3a9ad9",
  heroEyebrow: "23 RÍOS · CERVECERÍA ARTESANAL",
  heroTitle: "Cerveza de fábrica.",
  heroHighlight: "Hecha acá, tomada acá.",
  heroDescription: "Explorá nuestras cervezas artesanales y encontrá la combinación perfecta con nuestra cocina. Tu mozo digital te guía.",
  contactEmail: "",
  phone: "",
  currency: "ARS",
  defaultLanguage: "es",
  orderNotifications: true,
  serviceNotifications: true,
  weeklySummary: false,
  orderToken: "",
  eventModeActive: false,
};

const nn = { basis: "—", calories: "—", fats: "—", proteins: "—", carbs: "—", sugars: "—" };

const beerServingsClassic = [
  { label: "Media pinta", volume: "250 cc", price: 2800 },
  { label: "Pinta", volume: "500 cc", price: 5000 },
  { label: "Jarra", volume: "1 L", price: 9000 },
];
const beerServingsIPA = [
  { label: "Media pinta", volume: "250 cc", price: 3000 },
  { label: "Pinta", volume: "500 cc", price: 5500 },
  { label: "Jarra", volume: "1 L", price: 10000 },
];

export const DEFAULT_PRODUCTS: Product[] = [
  // ── CERVEZAS CLÁSICAS ─────────────────────────────────────────────────────
  {
    id: "golden",
    name: "Golden",
    category: "Cervezas",
    description: "Ale Americana de color dorado pálido, muy cristalina. Fácil de beber y orientada hacia la malta, con un final levemente ácido brindado por el trigo. Balanceada y limpia, sin aromas ni sabores agresivos. · Atuel",
    tag: "Atuel",
    note: "",
    group: "Cervezas clásicas",
    relatedIds: ["papas-clasicas", "nuggets-brocoli", "picada"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "Golden",
    price: 5000,
    nutrition: nn,
    beerProfile: { style: "Golden Ale", descriptors: ["Dorada", "Refrescante", "Balanceada"], ibu: "20", abv: "4,5%", srm: "8 EBC" },
    servings: beerServingsClassic,
  },
  {
    id: "scottish",
    name: "Scottish",
    category: "Cervezas",
    description: "Ale Escocesa de color cobrizo oscuro y cristalino. Enfocada en la malta, con sabores tostados y acaramelados, fragancias frutadas de la fermentación. Resalta las maltas especiales con notas a frutos secos, pasas de uva, nueces y almendras. · Grande",
    tag: "Grande",
    note: "",
    group: "Cervezas clásicas",
    relatedIds: ["lomo-clasico", "picada", "smash-23"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "Scottish",
    price: 5000,
    nutrition: nn,
    beerProfile: { style: "Scottish Export", descriptors: ["Cobriza", "Caramelo", "Frutos secos"], ibu: "25", abv: "5,2%", srm: "40 EBC" },
    servings: beerServingsClassic,
  },
  {
    id: "ipa",
    name: "IPA",
    category: "Cervezas",
    description: "India Pale Ale Argenta balanceada hacia el lúpulo. Color dorado anaranjado cristalino, amargor alto pero agradable y redondo. Lúpulos herbales, especiados, resinosos y cítricos. Oro Copa Cervezas de América 2019 · Plata Mejor IPA de Sudamérica 2020. · Diamiante",
    tag: "Diamiante",
    note: "",
    group: "Cervezas clásicas",
    relatedIds: ["papas-23-rios", "smash-blue", "general-tso"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "IPA",
    price: 5500,
    nutrition: nn,
    beerProfile: { style: "IPA", descriptors: ["Cítrica", "Resinosa", "Premiada"], ibu: "52", abv: "5,0%", srm: "13 EBC" },
    servings: beerServingsIPA,
  },
  {
    id: "stout",
    name: "Stout",
    category: "Cervezas",
    description: "Cerveza negra de carácter marcadamente tostado, con aromas que recuerdan al café. Espuma cremosa y persistente. Amargor moderado y final medio que invita a seguir bebiéndola. Carbonatación baja para disfrutar de su cuerpo sedoso y liviano. · Mendoza",
    tag: "Mendoza",
    note: "",
    group: "Cervezas clásicas",
    relatedIds: ["birramisu", "brownie", "picada"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "Stout",
    price: 5000,
    nutrition: nn,
    beerProfile: { style: "Stout", descriptors: ["Negra", "Café", "Sedosa"], ibu: "30", abv: "4,5%", srm: "70 EBC" },
  },
  {
    id: "honey",
    name: "Honey",
    category: "Cervezas",
    description: "Cerveza de color dorado intenso con miel de Jarilla 100% mendocina. Aroma balanceado entre malta de cebada, trigo malteado y miel. En boca domina el dulzor moderado de la jarilla; el amargor final lo aporta el lúpulo Victoria de la Patagonia. · Tunuyán",
    tag: "Tunuyán",
    note: "",
    group: "Cervezas clásicas",
    relatedIds: ["papas-clasicas", "provoleta", "lomo-clasico"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "Honey",
    price: 5000,
    nutrition: nn,
    beerProfile: { style: "Honey Ale", descriptors: ["Miel", "Floral", "Mendocina"], ibu: "23", abv: "5,0%", srm: "12 EBC" },
  },

  // ── CERVEZAS ESPECIALES ───────────────────────────────────────────────────
  {
    id: "lager",
    name: "Lager",
    category: "Cervezas",
    description: "Cerveza alemana de color dorado, aroma suave y amargor medio.",
    tag: "Especial",
    note: "",
    group: "Cervezas especiales",
    relatedIds: ["papas-clasicas", "picada", "empanadas-carne"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "Lager",
    price: 4500,
    nutrition: nn,
    beerProfile: { style: "Lager", descriptors: ["Dorada", "Suave", "Alemana"], ibu: "—", abv: "—", srm: "—" },
  },
  {
    id: "american-ipa",
    name: "American IPA",
    category: "Cervezas",
    description: "American Pale Ale de alta fermentación con aroma y sabor marcado a lúpulos americanos. Características frutales y cítricas: melón, durazno, ananá y cáscara de pomelo. Color de dorado pálido a ámbar. Edición limitada. · Picheuta",
    tag: "Picheuta",
    note: "",
    group: "Cervezas especiales",
    relatedIds: ["smash-blue", "papas-23-rios", "general-tso"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "American IPA",
    price: 6000,
    nutrition: nn,
    beerProfile: { style: "American Pale Ale", descriptors: ["Tropical", "Cítrica", "Frutal"], ibu: "32", abv: "6,0%", srm: "17 EBC" },
  },
  {
    id: "orange-wheat",
    name: "Orange Wheat",
    category: "Cervezas",
    description: "Color pajizo pálido y aspecto nublado por levadura en suspensión y almidón de trigo. Espuma blanca, densa y persistente. Notas especiadas con fondo cítrico a naranja. Suave en el paladar con final ligeramente ácido. Elaborada con trigo y piel de naranja. · Salvaje",
    tag: "Salvaje",
    note: "Consultar disponibilidad.",
    group: "Cervezas especiales",
    relatedIds: ["pizza-napolitana", "nuggets-brocoli", "provoleta"],
    attributes: [],
    allergens: ["Gluten"],
    beerStyle: "Orange Wheat",
    price: 0,
    nutrition: nn,
    beerProfile: { style: "Orange Wheat", descriptors: ["Naranja", "Trigo", "Refrescante"], ibu: "18", abv: "4,0%", srm: "5 EBC" },
  },

  // ── ENTRADAS ──────────────────────────────────────────────────────────────
  {
    id: "papas-clasicas",
    name: "Papas clásicas",
    image: "/images/23rios/papas-clasicas.png",
    category: "Cocina",
    description: "Papas fritas crujientes con sal condimentada.",
    tag: "Entrada",
    note: "",
    group: "Entradas",
    relatedIds: ["golden", "ipa", "lager"],
    attributes: ["Vegetariano", "Sin TACC"],
    allergens: [],
    price: 10200,
    nutrition: nn,
  },
  {
    id: "papas-23-rios",
    name: "Papas 23 Ríos",
    image: "/images/23rios/papas-23rios.png",
    category: "Cocina",
    description: "Papas fritas crujientes con salchichas alemanas y queso cheddar.",
    tag: "Entrada",
    note: "",
    group: "Entradas",
    relatedIds: ["golden", "scottish", "lager"],
    attributes: [],
    allergens: ["Lácteos"],
    price: 10100,
    nutrition: nn,
  },
  {
    id: "nuggets-brocoli",
    name: "Nuggets de Brócoli",
    image: "/images/23rios/nuggets-brocoli.png",
    category: "Cocina",
    description: "Bocados de brócoli con lactonesa de ajo, acompañados con guarnición de papas fritas.",
    tag: "Entrada",
    note: "",
    group: "Entradas",
    relatedIds: ["golden", "ipa", "lager"],
    attributes: ["Vegetariano"],
    allergens: ["Gluten"],
    price: 10800,
    nutrition: nn,
  },
  {
    id: "picada",
    name: "Picada de fiambres",
    image: "/images/23rios/picada.png",
    category: "Cocina",
    description: "Selección de queso azul, provolone, jamón cocido, bondiola y salamín. Acompañado con dips de mayonesa y pan de bagazo.",
    tag: "Para compartir",
    note: "",
    group: "Entradas",
    relatedIds: ["scottish", "honey", "golden"],
    attributes: ["Para compartir"],
    allergens: ["Gluten", "Lácteos"],
    price: 17500,
    nutrition: nn,
  },
  {
    id: "provoleta",
    name: "Provoleta Fundida",
    image: "/images/23rios/provoleta.png",
    category: "Cocina",
    description: "Medallón de 180 gr de provoleta con pesto casero, mix de verdes y encurtidos de cebolla morada.",
    tag: "Entrada",
    note: "",
    group: "Entradas",
    relatedIds: ["honey", "scottish", "golden"],
    attributes: ["Vegetariano"],
    allergens: ["Lácteos"],
    price: 19600,
    nutrition: nn,
  },
  {
    id: "general-tso",
    name: "Poderoso General Tso",
    image: "/images/23rios/general-tso.png",
    category: "Cocina",
    description: "Pollo crocante con salsa agridulce picante.",
    tag: "Entrada",
    note: "",
    group: "Entradas",
    relatedIds: ["ipa", "american-ipa", "golden"],
    attributes: [],
    allergens: ["Gluten", "Soja"],
    price: 14100,
    nutrition: nn,
  },
  {
    id: "experiencia-alemana",
    name: "Experiencia Alemana",
    image: "/images/23rios/experiencia-alemana.png",
    category: "Cocina",
    description: "Salchichas alemanas y polacas, coleslaw, ensalada alemana, chucrut, currywurst y papas fritas. Con pan de bagazo.",
    tag: "Para compartir",
    note: "",
    group: "Entradas",
    relatedIds: ["lager", "scottish", "golden"],
    attributes: ["Para compartir"],
    allergens: ["Gluten"],
    price: 41000,
    nutrition: nn,
  },

  // ── PIZZAS ────────────────────────────────────────────────────────────────
  {
    id: "pizza-muzzarella",
    name: "Muzzarella",
    image: "/images/23rios/pizza-muzzarella.png",
    category: "Cocina",
    description: "Pizza de masa madre, muzzarella, chimichurri casero y aceitunas verdes.",
    tag: "Pizza",
    note: "",
    group: "Pizzas",
    relatedIds: ["golden", "ipa", "lager"],
    attributes: ["Vegetariano", "Para compartir"],
    allergens: ["Gluten", "Lácteos"],
    price: 25100,
    nutrition: nn,
  },
  {
    id: "pizza-napolitana",
    name: "Napolitana",
    image: "/images/23rios/pizza-napolitana.png",
    category: "Cocina",
    description: "Pizza de masa madre, muzzarella, chimichurri casero, tomate fresco, pesto casero y aceitunas verdes.",
    tag: "Pizza",
    note: "",
    group: "Pizzas",
    relatedIds: ["golden", "honey", "lager"],
    attributes: ["Vegetariano", "Para compartir"],
    allergens: ["Gluten", "Lácteos"],
    price: 24300,
    nutrition: nn,
  },
  {
    id: "pizza-calabresa",
    name: "Calabresa",
    image: "/images/23rios/pizza-calabresa.png",
    category: "Cocina",
    description: "Pizza de masa madre, muzzarella, chimichurri casero, salamín y aceitunas verdes.",
    tag: "Pizza",
    note: "Precio pendiente de confirmación.",
    group: "Pizzas",
    relatedIds: ["scottish", "ipa", "golden"],
    attributes: ["Para compartir"],
    allergens: ["Gluten", "Lácteos"],
    price: 0,
    nutrition: nn,
  },
  {
    id: "pizza-americana",
    name: "Americana",
    image: "/images/23rios/pizza-americana.png",
    category: "Cocina",
    description: "Pizza de masa madre, muzzarella, chimichurri casero, panceta crocante y huevo frito.",
    tag: "Pizza",
    note: "Precio pendiente de confirmación.",
    group: "Pizzas",
    relatedIds: ["golden", "scottish", "ipa"],
    attributes: ["Para compartir"],
    allergens: ["Gluten", "Lácteos", "Huevo"],
    price: 0,
    nutrition: nn,
  },

  // ── ENTRE PANES Y MÁS ────────────────────────────────────────────────────
  {
    id: "smash-blue",
    name: "Smash Blue",
    image: "/images/23rios/smash-blue.png",
    category: "Cocina",
    description: "Pan de papa, doble medallón de carne, cheddar, queso azul y huevo frito.",
    tag: "Hamburguesa",
    note: "",
    group: "Entre panes y más",
    relatedIds: ["ipa", "american-ipa", "scottish"],
    attributes: [],
    allergens: ["Gluten", "Lácteos", "Huevo"],
    price: 15600,
    nutrition: nn,
  },
  {
    id: "smash-doble-queso",
    name: "Smash doble queso",
    image: "/images/23rios/smash-doble-queso.png",
    category: "Cocina",
    description: "Pan de papa, doble medallón de carne, doble cheddar.",
    tag: "Hamburguesa",
    note: "",
    group: "Entre panes y más",
    relatedIds: ["golden", "ipa", "lager"],
    attributes: [],
    allergens: ["Gluten", "Lácteos"],
    price: 15000,
    nutrition: nn,
  },
  {
    id: "smash-23",
    name: "Smash 23",
    image: "/images/23rios/smash-23.png",
    category: "Cocina",
    description: "Pan de papa, doble medallón de carne, cebolla caramelizada, salsa tasty y panceta crocante.",
    tag: "Hamburguesa",
    note: "",
    group: "Entre panes y más",
    relatedIds: ["scottish", "golden", "honey"],
    attributes: [],
    allergens: ["Gluten"],
    price: 15500,
    nutrition: nn,
  },
  {
    id: "lomo-clasico",
    name: "Lomo clásico 30 cm",
    image: "/images/23rios/lomo-clasico.png",
    category: "Cocina",
    description: "Pan francés, lomo liso, salsa de tomate, huevo, mayonesa de ajo, lechuga, queso y jamón.",
    tag: "Sándwich",
    note: "",
    group: "Entre panes y más",
    relatedIds: ["scottish", "honey", "golden"],
    attributes: [],
    allergens: ["Gluten", "Lácteos", "Huevo"],
    price: 27700,
    nutrition: nn,
  },

  // ── EMPANADAS ARTESANALES ─────────────────────────────────────────────────
  {
    id: "empanada-verdura",
    name: "Empanada de verdura",
    category: "Cocina",
    description: "Rellena de vegetales suavemente especiados.",
    tag: "Empanada",
    note: "",
    group: "Empanadas artesanales",
    relatedIds: ["golden", "lager"],
    attributes: ["Vegetariano"],
    allergens: ["Gluten"],
    price: 2700,
    nutrition: nn,
  },
  {
    id: "empanadas-carne",
    name: "Dúo empanadas de carne",
    category: "Cocina",
    description: "Los clásicos pasteles fritos (2 unidades).",
    tag: "Empanada",
    note: "",
    group: "Empanadas artesanales",
    relatedIds: ["golden", "scottish", "lager"],
    attributes: [],
    allergens: ["Gluten"],
    price: 5000,
    nutrition: nn,
  },

  // ── MENÚ INFANTIL ─────────────────────────────────────────────────────────
  {
    id: "kid-nuggets",
    name: "Nuggets de Brócoli Kid",
    category: "Cocina",
    description: "4 unidades de nuggets de brócoli, papas fritas, gaseosa y juguete a elección.",
    tag: "Menú infantil",
    note: "",
    group: "Menú infantil",
    relatedIds: ["coca-cola", "sprite"],
    attributes: ["Vegetariano"],
    allergens: ["Gluten"],
    price: 18000,
    nutrition: nn,
  },
  {
    id: "kid-hamburguesa",
    name: "Hamburguesa Cheese Kid",
    category: "Cocina",
    description: "Hamburguesa kid con cheddar, papas fritas, gaseosa y juguete a elección.",
    tag: "Menú infantil",
    note: "",
    group: "Menú infantil",
    relatedIds: ["coca-cola", "sprite"],
    attributes: [],
    allergens: ["Gluten", "Lácteos"],
    price: 18000,
    nutrition: nn,
  },

  // ── POSTRES ───────────────────────────────────────────────────────────────
  {
    id: "birramisu",
    name: "Birramisu",
    image: "/images/23rios/birramisu.png",
    category: "Cocina",
    description: "Vainillas embebidas en nuestra cerveza Stout y almíbar artesanal, cubiertas con crema suave de queso.",
    tag: "Postre",
    note: "",
    group: "Postres",
    relatedIds: ["stout"],
    attributes: [],
    allergens: ["Gluten", "Lácteos", "Huevo"],
    price: 6500,
    nutrition: nn,
  },
  {
    id: "flan",
    name: "Flan",
    image: "/images/23rios/flan.png",
    category: "Cocina",
    description: "Flan casero de la casa con dulce de leche y crema.",
    tag: "Postre",
    note: "",
    group: "Postres",
    relatedIds: ["stout", "honey"],
    attributes: [],
    allergens: ["Lácteos", "Huevo"],
    price: 6500,
    nutrition: nn,
  },
  {
    id: "lemon-pie",
    name: "Lemon Pie",
    category: "Cocina",
    description: "Base crocante de masa sablée, crema de limón intensa y merengue suave y aireado.",
    tag: "Postre",
    note: "",
    group: "Postres",
    relatedIds: ["honey", "golden"],
    attributes: [],
    allergens: ["Gluten", "Lácteos", "Huevo"],
    price: 6500,
    nutrition: nn,
  },
  {
    id: "brownie",
    name: "Brownie",
    category: "Cocina",
    description: "Brownie húmedo e intenso, coronado con dulce de leche cremoso y merengue suave.",
    tag: "Postre",
    note: "",
    group: "Postres",
    relatedIds: ["stout", "scottish"],
    attributes: [],
    allergens: ["Gluten", "Lácteos", "Huevo"],
    price: 6500,
    nutrition: nn,
  },

  // ── TRAGOS CLÁSICOS ───────────────────────────────────────────────────────
  {
    id: "fernet-branca",
    name: "Fernet Branca",
    category: "Bebidas",
    description: "Fernet Branca clásico.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 8000,
    nutrition: nn,
  },
  {
    id: "aperol-spritz",
    name: "Aperol Spritz",
    category: "Bebidas",
    description: "El aperitivo italiano por excelencia.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 9900,
    nutrition: nn,
  },
  {
    id: "cuba-libre",
    name: "Cuba Libre",
    category: "Bebidas",
    description: "Ron Havana Dorado y Coca Cola.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 8900,
    nutrition: nn,
  },
  {
    id: "vermouth-rosso",
    name: "Vermouth Rosso",
    category: "Bebidas",
    description: "Con soda, hielo y rodaja de naranja.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 7000,
    nutrition: nn,
  },
  {
    id: "cynar",
    name: "Cynar",
    category: "Bebidas",
    description: "Cynar, menta, reducción de Stout y gaseosa de pomelo.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: ["stout"],
    attributes: [],
    allergens: [],
    price: 7100,
    nutrition: nn,
  },
  {
    id: "mojito-clasico",
    name: "Mojito Clásico",
    category: "Bebidas",
    description: "Ron Havana blanco, jugo de limón, menta, almíbar y soda.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 7600,
    nutrition: nn,
  },
  {
    id: "mojito-malibu",
    name: "Mojito Malibú",
    category: "Bebidas",
    description: "Ron Havana blanco y ron Malibú, jugo de limón, menta, almíbar y soda.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 9400,
    nutrition: nn,
  },
  {
    id: "campari",
    name: "Campari",
    category: "Bebidas",
    description: "Campari solo o con jugo de naranja o tónica.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 7000,
    nutrition: nn,
  },
  {
    id: "gin-gordons",
    name: "Gin Gordon's",
    category: "Bebidas",
    description: "Gin Gordon's y tónica con fruta o especia a elección.",
    tag: "Gin tónica",
    note: "Precio pendiente de confirmación.",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 0,
    nutrition: nn,
  },
  {
    id: "gin-beefeater",
    name: "Gin Beefeater",
    category: "Bebidas",
    description: "Gin Beefeater y tónica con fruta o especia a elección.",
    tag: "Gin tónica",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 10200,
    nutrition: nn,
  },
  {
    id: "gin-bulldog",
    name: "Gin Bulldog",
    category: "Bebidas",
    description: "Gin Bulldog y tónica con fruta o especia a elección.",
    tag: "Gin tónica",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 12700,
    nutrition: nn,
  },
  {
    id: "negroni",
    name: "Negroni",
    category: "Bebidas",
    description: "Gin Gordon's, Carpano Rosso y Campari.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 7200,
    nutrition: nn,
  },
  {
    id: "boulevardier",
    name: "Boulevardier",
    category: "Bebidas",
    description: "Bourbon, Vermouth Rosso y Campari. Potente, equilibrado y con alma italiana.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 8700,
    nutrition: nn,
  },
  {
    id: "garibaldi",
    name: "Garibaldi",
    category: "Bebidas",
    description: "Campari y jugo de naranja natural. Dulce, ácido y de espíritu italiano.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 7000,
    nutrition: nn,
  },
  {
    id: "daiquiri",
    name: "Daiquiri",
    category: "Bebidas",
    description: "Daiquiri de frutas de estación.",
    tag: "Trago",
    note: "",
    group: "Tragos clásicos",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 8000,
    nutrition: nn,
  },

  // ── PARA PREPARAR ─────────────────────────────────────────────────────────
  {
    id: "prep-fernet",
    name: "Fernet + Coca",
    category: "Bebidas",
    description: "Fernet con Coca Cola 500 ml.",
    tag: "Para preparar",
    note: "",
    group: "Para preparar",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 13500,
    nutrition: nn,
  },
  {
    id: "prep-ron",
    name: "Ron + Coca",
    category: "Bebidas",
    description: "Ron Havana Dorado con Coca Cola 500 ml.",
    tag: "Para preparar",
    note: "",
    group: "Para preparar",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 15500,
    nutrition: nn,
  },
  {
    id: "prep-vodka",
    name: "Vodka + Red Bull",
    category: "Bebidas",
    description: "Vodka con lata de Red Bull.",
    tag: "Para preparar",
    note: "",
    group: "Para preparar",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 11700,
    nutrition: nn,
  },
  {
    id: "prep-jager",
    name: "Jäger + Red Bull",
    category: "Bebidas",
    description: "Jägermeister con lata de Red Bull.",
    tag: "Para preparar",
    note: "",
    group: "Para preparar",
    relatedIds: [],
    attributes: [],
    allergens: [],
    price: 28200,
    nutrition: nn,
  },

  // ── WHISKIES ──────────────────────────────────────────────────────────────
  {
    id: "whisky-red-label",
    name: "Red Label",
    category: "Bebidas",
    description: "Johnnie Walker Red Label.",
    tag: "Whisky",
    note: "",
    group: "Whiskies",
    relatedIds: [],
    attributes: [],
    allergens: ["Gluten"],
    price: 8500,
    nutrition: nn,
  },
  {
    id: "whisky-jim-beam",
    name: "Jim Beam",
    category: "Bebidas",
    description: "Bourbon americano.",
    tag: "Whisky",
    note: "",
    group: "Whiskies",
    relatedIds: [],
    attributes: [],
    allergens: ["Gluten"],
    price: 8500,
    nutrition: nn,
  },
  {
    id: "whisky-double-black",
    name: "Double Black",
    category: "Bebidas",
    description: "Johnnie Walker Double Black.",
    tag: "Whisky",
    note: "",
    group: "Whiskies",
    relatedIds: [],
    attributes: [],
    allergens: ["Gluten"],
    price: 12500,
    nutrition: nn,
  },

  // ── VINOS ─────────────────────────────────────────────────────────────────
  {
    id: "malbec",
    name: "Las Perdices Malbec",
    category: "Bebidas",
    description: "Copa de Malbec Las Perdices.",
    tag: "Vino",
    note: "",
    group: "Vinos",
    relatedIds: ["lomo-clasico", "picada"],
    attributes: [],
    allergens: [],
    price: 14000,
    nutrition: nn,
  },
  {
    id: "cabernet-franc",
    name: "Cabernet Franc",
    category: "Bebidas",
    description: "Copa de Cabernet Franc.",
    tag: "Vino",
    note: "",
    group: "Vinos",
    relatedIds: ["lomo-clasico", "picada"],
    attributes: [],
    allergens: [],
    price: 14000,
    nutrition: nn,
  },
  {
    id: "sauvignon-blanc",
    name: "Sauvignon Blanc",
    category: "Bebidas",
    description: "Copa de Sauvignon Blanc Chac chac.",
    tag: "Vino",
    note: "",
    group: "Vinos",
    relatedIds: ["provoleta", "pizza-napolitana"],
    attributes: [],
    allergens: [],
    price: 14000,
    nutrition: nn,
  },
  {
    id: "reserva-malbec",
    name: "Las Perdices Reserva Malbec",
    category: "Bebidas",
    description: "Copa de Malbec Reserva Las Perdices.",
    tag: "Vino",
    note: "",
    group: "Vinos",
    relatedIds: ["lomo-clasico", "picada"],
    attributes: [],
    allergens: [],
    price: 18000,
    nutrition: nn,
  },

  // ── COMBOS ────────────────────────────────────────────────────────────────
  {
    id: "combo-fernet",
    name: "Fernet + Coca 2,25 lts",
    category: "Bebidas",
    description: "Botella de Fernet Branca con Coca Cola 2,25 litros.",
    tag: "Combo",
    note: "",
    group: "Combos",
    relatedIds: [],
    attributes: ["Para compartir"],
    allergens: [],
    price: 70000,
    nutrition: nn,
  },
  {
    id: "combo-ron",
    name: "Ron Havana + Coca 2,25 lts",
    category: "Bebidas",
    description: "Botella de Ron Havana Dorado con Coca Cola 2,25 litros.",
    tag: "Combo",
    note: "",
    group: "Combos",
    relatedIds: [],
    attributes: ["Para compartir"],
    allergens: [],
    price: 74000,
    nutrition: nn,
  },
  {
    id: "combo-vodka",
    name: "Vodka Skyy + Sprite 2,25 lts",
    category: "Bebidas",
    description: "Botella de Vodka Skyy con Sprite 2,25 litros.",
    tag: "Combo",
    note: "",
    group: "Combos",
    relatedIds: [],
    attributes: ["Para compartir"],
    allergens: [],
    price: 60000,
    nutrition: nn,
  },
  {
    id: "combo-gin-gordons",
    name: "Gin Gordon's + Tónica 1,5 lts",
    category: "Bebidas",
    description: "Botella de Gin Gordon's con tónica 1,5 litros.",
    tag: "Combo",
    note: "",
    group: "Combos",
    relatedIds: [],
    attributes: ["Para compartir"],
    allergens: [],
    price: 74000,
    nutrition: nn,
  },
  {
    id: "combo-gin-beefeater",
    name: "Gin Beefeater + Tónica 1,5 lts",
    category: "Bebidas",
    description: "Botella de Gin Beefeater con tónica 1,5 litros.",
    tag: "Combo",
    note: "",
    group: "Combos",
    relatedIds: [],
    attributes: ["Para compartir"],
    allergens: [],
    price: 78000,
    nutrition: nn,
  },

  // ── SIN ALCOHOL / GASEOSAS ────────────────────────────────────────────────
  {
    id: "coca-cola",
    name: "Coca Cola 500 ml",
    category: "Bebidas",
    description: "Coca Cola 500 ml.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 3500,
    nutrition: nn,
  },
  {
    id: "coca-zero",
    name: "Coca Zero 500 ml",
    category: "Bebidas",
    description: "Coca Cola Zero 500 ml.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 3500,
    nutrition: nn,
  },
  {
    id: "sprite",
    name: "Sprite 500 ml",
    category: "Bebidas",
    description: "Sprite 500 ml.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 3500,
    nutrition: nn,
  },
  {
    id: "agua-saborizada",
    name: "Agua saborizada",
    category: "Bebidas",
    description: "Agua saborizada.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 3500,
    nutrition: nn,
  },
  {
    id: "tonica",
    name: "Lata tónica 268 ml",
    category: "Bebidas",
    description: "Lata de agua tónica 268 ml.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: ["gin-gordons", "gin-beefeater", "gin-bulldog"],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 3000,
    nutrition: nn,
  },
  {
    id: "pomelo",
    name: "Lata pomelo 269 ml",
    category: "Bebidas",
    description: "Lata de gaseosa de pomelo 269 ml.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 3000,
    nutrition: nn,
  },
  {
    id: "agua",
    name: "Agua sin / con gas",
    category: "Bebidas",
    description: "Agua mineral sin o con gas.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 3000,
    nutrition: nn,
  },
  {
    id: "limonada",
    name: "Limonada",
    category: "Bebidas",
    description: "Limonada natural.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol"],
    allergens: [],
    price: 6000,
    nutrition: nn,
  },
  {
    id: "jarra-limonada",
    name: "Jarra de Limonada",
    category: "Bebidas",
    description: "Jarra de limonada natural para compartir.",
    tag: "Sin alcohol",
    note: "",
    group: "Sin alcohol / Gaseosas",
    relatedIds: [],
    attributes: ["Sin alcohol", "Para compartir"],
    allergens: [],
    price: 9000,
    nutrition: nn,
  },
];

export const DEFAULT_MENU_SETTINGS: MenuSettings = {
  foodGroups: ["Entradas", "Pizzas", "Entre panes y más", "Empanadas artesanales", "Menú infantil", "Postres"],
  foodPreferences: ["Vegetariano", "Sin TACC", "Para compartir"],
  allergenOptions: ["Gluten", "Lácteos", "Huevo", "Maní", "Soja"],
  drinkGroups: ["Cervezas clásicas", "Cervezas especiales", "Tragos clásicos", "Para preparar", "Whiskies", "Vinos", "Combos", "Sin alcohol / Gaseosas"],
  beerStyles: ["Golden", "Scottish", "IPA", "Stout", "Honey", "Lager", "American IPA", "Orange Wheat"],
};

export function cloneDefaultProducts() {
  return JSON.parse(JSON.stringify(DEFAULT_PRODUCTS)) as Product[];
}

export function mergeDefaultProductImages(products: Product[]) {
  const defaultImages = new Map(DEFAULT_PRODUCTS.map((product) => [product.id, product.image]));
  return products.map((product) => {
    if (Object.prototype.hasOwnProperty.call(product, "image")) return product;
    const image = defaultImages.get(product.id);
    return image ? { ...product, image } : product;
  });
}

export function cloneDefaultSettings() {
  return JSON.parse(JSON.stringify(DEFAULT_MENU_SETTINGS)) as MenuSettings;
}
