export type Language = "es" | "pt" | "en" | "fr" | "it" | "de";

export const languageOptions: { code: Language; short: string; label: string }[] = [
  { code: "es", short: "ES", label: "Español" },
  { code: "pt", short: "PT", label: "Português" },
  { code: "en", short: "EN", label: "English" },
  { code: "fr", short: "FR", label: "Français" },
  { code: "it", short: "IT", label: "Italiano" },
  { code: "de", short: "DE", label: "Deutsch" },
];

const dictionaries: Record<Exclude<Language, "es">, Record<string, string>> = {
  pt: {
    "MENÚ GENERAL": "MENU GERAL", "Mis pedidos": "Meus pedidos", "Preguntale al mozo": "Pergunte ao garçom",
    "MENÚ DIGITAL · 23 RÍOS": "MENU DIGITAL · 23 RÍOS", "Elegí con los ojos.": "Escolha com os olhos.", "Disfrutá a tu manera.": "Aproveite do seu jeito.",
    "Explorá nuestros productos con fotos reales o contanos qué te gusta y te ayudamos a encontrar la mejor combinación.": "Explore nossos produtos com fotos reais ou conte o que você gosta e ajudamos a encontrar a melhor combinação.",
    "Ver la carta": "Ver o menu", "Quiero una recomendación": "Quero uma recomendação", "Fotos reales": "Fotos reais", "Sin imágenes genéricas": "Sem imagens genéricas",
    "Cerveza propia": "Cerveja própria", "De la fábrica a tu pinta": "Da fábrica ao seu copo", "Elegí mejor": "Escolha melhor", "Con ayuda cuando la necesites": "Com ajuda quando precisar",
    "Llamar al mozo": "Chamar o garçom", "Solicitar la cuenta": "Pedir a conta", "Pedido rápido": "Pedido rápido", "Personalizable": "Personalizável",
    "NUESTRA CARTA": "NOSSO MENU", "Algo para cada momento.": "Algo para cada momento.", "Buscar en el menú": "Buscar no menu", "Comida": "Comida", "Bebida": "Bebida",
    "Tipo de comida": "Tipo de comida", "Preferencias": "Preferências", "Evitar alérgenos": "Evitar alérgenos", "Tipo de bebida": "Tipo de bebida", "Estilo de cerveza": "Estilo de cerveja",
    "Papas fritas": "Batatas fritas", "Lomos": "Sanduíches de lombo", "Pizzas": "Pizzas", "Vegetariano": "Vegetariano", "Sin TACC": "Sem glúten", "Para compartir": "Para compartilhar",
    "Gluten": "Glúten", "Lácteos": "Laticínios", "Huevo": "Ovo", "Gaseosas": "Refrigerantes", "Agua saborizada": "Água saborizada", "Cerveza": "Cerveja",
    "Rubia": "Clara", "Roja": "Vermelha", "Negra": "Escura", "Limpiar filtros": "Limpar filtros", "resultado": "resultado", "resultados": "resultados",
    "Tocá una foto para verla completa.": "Toque na foto para vê-la inteira.", "Mostramos el producto real, en primer plano y sin sorpresas.": "Mostramos o produto real, em destaque e sem surpresas.",
    "Desde": "A partir de", "Precio demo": "Preço demonstrativo", "Ver detalle": "Ver detalhes", "Foto real pendiente": "Foto real pendente",
    "FORMATO": "FORMATO", "¿Cómo la querés?": "Como você prefere?", "Precios de muestra": "Preços demonstrativos", "Media pinta": "Meia pinta", "Pinta": "Pinta", "Jarra": "Jarra",
    "INFORMACIÓN NUTRICIONAL": "INFORMAÇÃO NUTRICIONAL", "Valores nutricionales": "Valores nutricionais", "Calorías": "Calorias", "Grasas": "Gorduras", "Proteínas": "Proteínas", "Carbohidratos": "Carboidratos", "Azúcares": "Açúcares", "Alérgenos": "Alérgenos",
    "Información provisional": "Informação provisória", "Agregar al carrito": "Adicionar ao carrinho", "Agregado al carrito": "Adicionado ao carrinho", "Se puede acompañar con": "Pode acompanhar com",
    "CARRITO ABIERTO": "CARRINHO ABERTO", "PEDIDO LANZADO": "PEDIDO ENVIADO", "Revisar carrito": "Revisar carrinho", "Ver estado del pedido": "Ver estado do pedido",
    "Revisá antes de lanzarlo": "Revise antes de enviar", "Cerrar carrito y lanzar pedido": "Fechar carrinho e enviar pedido", "Cerrar pedido": "Encerrar pedido", "Total": "Total",
    "HISTORIAL LOCAL": "HISTÓRICO LOCAL", "En preparación": "Em preparação", "Cerrado": "Encerrado", "Todavía no lanzaste pedidos": "Você ainda não enviou pedidos",
    "Lomo de la casa": "Lombo da casa", "Papas para compartir": "Batatas para compartilhar", "Pizza de la casa": "Pizza da casa", "Gaseosa": "Refrigerante",
    "Lomo completo con papas, acompañado por una pinta artesanal.": "Sanduíche de lombo completo com batatas, acompanhado de uma pinta artesanal.",
    "Papas especiadas y una cerveza dorada, una combinación bien cervecera.": "Batatas temperadas e uma cerveja dourada, uma combinação perfeita.",
    "Masa, salsa e ingredientes a confirmar con la carta oficial.": "Massa, molho e ingredientes a confirmar no menu oficial.",
    "Cerveza cobriza, maltosa y de cuerpo medio, con notas de caramelo y tostado.": "Cerveja acobreada, maltada e de corpo médio, com notas de caramelo e tostado.",
    "Cerveza rubia ligera, refrescante y equilibrada, con perfil suave de malta y lúpulo.": "Cerveja clara, leve, refrescante e equilibrada, com perfil suave de malte e lúpulo.",
    "Cerveza oscura y cremosa, con amargor moderado y notas tostadas de café y chocolate.": "Cerveja escura e cremosa, com amargor moderado e notas tostadas de café e chocolate.",
    "Opciones y tamaños pendientes de confirmar con la carta oficial.": "Opções e tamanhos pendentes de confirmação no menu oficial.", "Sabores y presentaciones pendientes de confirmar.": "Sabores e apresentações pendentes de confirmação."
  },
  en: {
    "MENÚ GENERAL": "MAIN MENU", "Mis pedidos": "My orders", "Preguntale al mozo": "Ask the waiter", "MENÚ DIGITAL · 23 RÍOS": "DIGITAL MENU · 23 RÍOS",
    "Elegí con los ojos.": "Choose with your eyes.", "Disfrutá a tu manera.": "Enjoy it your way.", "Explorá nuestros productos con fotos reales o contanos qué te gusta y te ayudamos a encontrar la mejor combinación.": "Explore our products with real photos or tell us what you like and we will help you find the best combination.",
    "Ver la carta": "View menu", "Quiero una recomendación": "I want a recommendation", "Fotos reales": "Real photos", "Sin imágenes genéricas": "No stock images", "Cerveza propia": "Our own beer", "De la fábrica a tu pinta": "From our brewery to your glass", "Elegí mejor": "Choose better", "Con ayuda cuando la necesites": "Help whenever you need it",
    "Llamar al mozo": "Call the waiter", "Solicitar la cuenta": "Request the bill", "Pedido rápido": "Quick request", "Personalizable": "Customizable", "NUESTRA CARTA": "OUR MENU", "Algo para cada momento.": "Something for every moment.", "Buscar en el menú": "Search the menu",
    "Comida": "Food", "Bebida": "Drinks", "Tipo de comida": "Food type", "Preferencias": "Preferences", "Evitar alérgenos": "Avoid allergens", "Tipo de bebida": "Drink type", "Estilo de cerveza": "Beer style",
    "Papas fritas": "French fries", "Lomos": "Steak sandwiches", "Pizzas": "Pizzas", "Vegetariano": "Vegetarian", "Sin TACC": "Gluten-free", "Para compartir": "To share", "Gluten": "Gluten", "Lácteos": "Dairy", "Huevo": "Egg", "Gaseosas": "Soft drinks", "Agua saborizada": "Flavored water", "Cerveza": "Beer", "Rubia": "Blonde", "Roja": "Red", "Negra": "Dark", "Limpiar filtros": "Clear filters", "resultado": "result", "resultados": "results",
    "Tocá una foto para verla completa.": "Tap a photo to view it in full.", "Mostramos el producto real, en primer plano y sin sorpresas.": "We show the real product up close, with no surprises.", "Desde": "From", "Precio demo": "Demo price", "Ver detalle": "View details", "Foto real pendiente": "Real photo pending",
    "FORMATO": "SIZE", "¿Cómo la querés?": "How would you like it?", "Precios de muestra": "Sample prices", "Media pinta": "Half pint", "Pinta": "Pint", "Jarra": "Pitcher",
    "INFORMACIÓN NUTRICIONAL": "NUTRITION INFORMATION", "Valores nutricionales": "Nutrition facts", "Calorías": "Calories", "Grasas": "Fat", "Proteínas": "Protein", "Carbohidratos": "Carbohydrates", "Azúcares": "Sugars", "Alérgenos": "Allergens",
    "Información provisional": "Provisional information", "Agregar al carrito": "Add to cart", "Agregado al carrito": "Added to cart", "Se puede acompañar con": "Pairs well with",
    "CARRITO ABIERTO": "OPEN CART", "PEDIDO LANZADO": "ORDER SENT", "Revisar carrito": "Review cart", "Ver estado del pedido": "View order status", "Revisá antes de lanzarlo": "Review before sending", "Cerrar carrito y lanzar pedido": "Close cart and send order", "Cerrar pedido": "Close order", "Total": "Total",
    "HISTORIAL LOCAL": "LOCAL HISTORY", "En preparación": "Being prepared", "Cerrado": "Closed", "Todavía no lanzaste pedidos": "You have not sent any orders yet",
    "Lomo de la casa": "House steak sandwich", "Papas para compartir": "Fries to share", "Pizza de la casa": "House pizza", "Gaseosa": "Soft drink",
    "Lomo completo con papas, acompañado por una pinta artesanal.": "Loaded steak sandwich with fries, served with a craft pint.", "Papas especiadas y una cerveza dorada, una combinación bien cervecera.": "Seasoned fries and a golden beer, a perfect brewery pairing.", "Masa, salsa e ingredientes a confirmar con la carta oficial.": "Dough, sauce and toppings to be confirmed with the official menu.",
    "Cerveza cobriza, maltosa y de cuerpo medio, con notas de caramelo y tostado.": "A copper-colored, malty, medium-bodied beer with caramel and toasted notes.", "Cerveza rubia ligera, refrescante y equilibrada, con perfil suave de malta y lúpulo.": "A light, refreshing and balanced blonde beer with a gentle malt and hop profile.", "Cerveza oscura y cremosa, con amargor moderado y notas tostadas de café y chocolate.": "A dark, creamy beer with moderate bitterness and roasted coffee and chocolate notes.", "Opciones y tamaños pendientes de confirmar con la carta oficial.": "Options and sizes are pending confirmation with the official menu.", "Sabores y presentaciones pendientes de confirmar.": "Flavors and presentations are pending confirmation."
  },
  fr: {
    "MENÚ GENERAL": "MENU GÉNÉRAL", "Mis pedidos": "Mes commandes", "Preguntale al mozo": "Demander au serveur", "MENÚ DIGITAL · 23 RÍOS": "MENU NUMÉRIQUE · 23 RÍOS", "Elegí con los ojos.": "Choisissez avec les yeux.", "Disfrutá a tu manera.": "Savourez à votre façon.", "Explorá nuestros productos con fotos reales o contanos qué te gusta y te ayudamos a encontrar la mejor combinación.": "Découvrez nos produits en vraies photos ou dites-nous ce que vous aimez pour trouver le meilleur accord.", "Ver la carta": "Voir le menu", "Quiero una recomendación": "Je veux une recommandation",
    "Fotos reales": "Photos réelles", "Sin imágenes genéricas": "Sans images génériques", "Cerveza propia": "Notre propre bière", "De la fábrica a tu pinta": "De la brasserie à votre verre", "Elegí mejor": "Mieux choisir", "Con ayuda cuando la necesites": "De l'aide quand vous en avez besoin", "Llamar al mozo": "Appeler le serveur", "Solicitar la cuenta": "Demander l'addition", "Pedido rápido": "Demande rapide", "Personalizable": "Personnalisable", "NUESTRA CARTA": "NOTRE MENU", "Algo para cada momento.": "Une envie pour chaque moment.", "Buscar en el menú": "Rechercher dans le menu",
    "Comida": "Plats", "Bebida": "Boissons", "Tipo de comida": "Type de plat", "Preferencias": "Préférences", "Evitar alérgenos": "Éviter les allergènes", "Tipo de bebida": "Type de boisson", "Estilo de cerveza": "Style de bière", "Papas fritas": "Frites", "Lomos": "Sandwichs au steak", "Pizzas": "Pizzas", "Vegetariano": "Végétarien", "Sin TACC": "Sans gluten", "Para compartir": "À partager", "Gluten": "Gluten", "Lácteos": "Produits laitiers", "Huevo": "Œuf", "Gaseosas": "Sodas", "Agua saborizada": "Eau aromatisée", "Cerveza": "Bière", "Rubia": "Blonde", "Roja": "Rousse", "Negra": "Brune", "Limpiar filtros": "Effacer les filtres", "resultado": "résultat", "resultados": "résultats",
    "Tocá una foto para verla completa.": "Touchez une photo pour l'agrandir.", "Mostramos el producto real, en primer plano y sin sorpresas.": "Nous montrons le vrai produit en gros plan, sans surprise.", "Desde": "À partir de", "Precio demo": "Prix indicatif", "Ver detalle": "Voir les détails", "Foto real pendiente": "Photo réelle à venir", "FORMATO": "FORMAT", "¿Cómo la querés?": "Quel format souhaitez-vous ?", "Precios de muestra": "Prix indicatifs", "Media pinta": "Demi-pinte", "Pinta": "Pinte", "Jarra": "Pichet",
    "INFORMACIÓN NUTRICIONAL": "INFORMATIONS NUTRITIONNELLES", "Valores nutricionales": "Valeurs nutritionnelles", "Calorías": "Calories", "Grasas": "Lipides", "Proteínas": "Protéines", "Carbohidratos": "Glucides", "Azúcares": "Sucres", "Alérgenos": "Allergènes", "Información provisional": "Informations provisoires", "Agregar al carrito": "Ajouter au panier", "Agregado al carrito": "Ajouté au panier", "Se puede acompañar con": "Peut être accompagné de",
    "CARRITO ABIERTO": "PANIER OUVERT", "PEDIDO LANZADO": "COMMANDE ENVOYÉE", "Revisar carrito": "Vérifier le panier", "Ver estado del pedido": "Voir l'état de la commande", "Revisá antes de lanzarlo": "Vérifiez avant l'envoi", "Cerrar carrito y lanzar pedido": "Fermer le panier et envoyer", "Cerrar pedido": "Clôturer la commande", "Total": "Total", "HISTORIAL LOCAL": "HISTORIQUE LOCAL", "En preparación": "En préparation", "Cerrado": "Clôturée", "Todavía no lanzaste pedidos": "Vous n'avez encore envoyé aucune commande",
    "Lomo de la casa": "Sandwich au steak maison", "Papas para compartir": "Frites à partager", "Pizza de la casa": "Pizza maison", "Gaseosa": "Soda", "Lomo completo con papas, acompañado por una pinta artesanal.": "Sandwich au steak garni avec frites, accompagné d'une pinte artisanale.", "Papas especiadas y una cerveza dorada, una combinación bien cervecera.": "Frites épicées et bière dorée, un accord parfait.", "Masa, salsa e ingredientes a confirmar con la carta oficial.": "Pâte, sauce et garnitures à confirmer avec le menu officiel.", "Cerveza cobriza, maltosa y de cuerpo medio, con notas de caramelo y tostado.": "Bière cuivrée, maltée et moyennement corsée, aux notes de caramel et de grillé.", "Cerveza rubia ligera, refrescante y equilibrada, con perfil suave de malta y lúpulo.": "Bière blonde légère, rafraîchissante et équilibrée, au profil doux de malt et de houblon.", "Cerveza oscura y cremosa, con amargor moderado y notas tostadas de café y chocolate.": "Bière brune et crémeuse, à l'amertume modérée et aux notes torréfiées de café et chocolat.", "Opciones y tamaños pendientes de confirmar con la carta oficial.": "Options et formats à confirmer avec le menu officiel.", "Sabores y presentaciones pendientes de confirmar.": "Saveurs et présentations à confirmer."
  },
  it: {
    "MENÚ GENERAL": "MENU GENERALE", "Mis pedidos": "I miei ordini", "Preguntale al mozo": "Chiedi al cameriere", "MENÚ DIGITAL · 23 RÍOS": "MENU DIGITALE · 23 RÍOS", "Elegí con los ojos.": "Scegli con gli occhi.", "Disfrutá a tu manera.": "Goditelo a modo tuo.", "Explorá nuestros productos con fotos reales o contanos qué te gusta y te ayudamos a encontrar la mejor combinación.": "Esplora i nostri prodotti con foto reali o raccontaci cosa ti piace e troveremo l'abbinamento migliore.", "Ver la carta": "Vedi il menu", "Quiero una recomendación": "Vorrei un consiglio", "Fotos reales": "Foto reali", "Sin imágenes genéricas": "Niente immagini generiche", "Cerveza propia": "Birra propria", "De la fábrica a tu pinta": "Dal birrificio al tuo bicchiere", "Elegí mejor": "Scegli meglio", "Con ayuda cuando la necesites": "Aiuto quando ne hai bisogno",
    "Llamar al mozo": "Chiama il cameriere", "Solicitar la cuenta": "Chiedi il conto", "Pedido rápido": "Richiesta rapida", "Personalizable": "Personalizzabile", "NUESTRA CARTA": "IL NOSTRO MENU", "Algo para cada momento.": "Qualcosa per ogni momento.", "Buscar en el menú": "Cerca nel menu", "Comida": "Cibo", "Bebida": "Bevande", "Tipo de comida": "Tipo di cibo", "Preferencias": "Preferenze", "Evitar alérgenos": "Evita allergeni", "Tipo de bebida": "Tipo di bevanda", "Estilo de cerveza": "Stile di birra", "Papas fritas": "Patatine fritte", "Lomos": "Panini con bistecca", "Pizzas": "Pizze", "Vegetariano": "Vegetariano", "Sin TACC": "Senza glutine", "Para compartir": "Da condividere", "Gluten": "Glutine", "Lácteos": "Latticini", "Huevo": "Uovo", "Gaseosas": "Bibite", "Agua saborizada": "Acqua aromatizzata", "Cerveza": "Birra", "Rubia": "Bionda", "Roja": "Rossa", "Negra": "Scura", "Limpiar filtros": "Cancella filtri", "resultado": "risultato", "resultados": "risultati",
    "Tocá una foto para verla completa.": "Tocca una foto per vederla intera.", "Mostramos el producto real, en primer plano y sin sorpresas.": "Mostriamo il prodotto reale in primo piano, senza sorprese.", "Desde": "Da", "Precio demo": "Prezzo dimostrativo", "Ver detalle": "Vedi dettagli", "Foto real pendiente": "Foto reale in arrivo", "FORMATO": "FORMATO", "¿Cómo la querés?": "Come la preferisci?", "Precios de muestra": "Prezzi dimostrativi", "Media pinta": "Mezza pinta", "Pinta": "Pinta", "Jarra": "Caraffa",
    "INFORMACIÓN NUTRICIONAL": "INFORMAZIONI NUTRIZIONALI", "Valores nutricionales": "Valori nutrizionali", "Calorías": "Calorie", "Grasas": "Grassi", "Proteínas": "Proteine", "Carbohidratos": "Carboidrati", "Azúcares": "Zuccheri", "Alérgenos": "Allergeni", "Información provisional": "Informazioni provvisorie", "Agregar al carrito": "Aggiungi al carrello", "Agregado al carrito": "Aggiunto al carrello", "Se puede acompañar con": "Può essere accompagnato da",
    "CARRITO ABIERTO": "CARRELLO APERTO", "PEDIDO LANZADO": "ORDINE INVIATO", "Revisar carrito": "Controlla il carrello", "Ver estado del pedido": "Vedi stato ordine", "Revisá antes de lanzarlo": "Controlla prima di inviare", "Cerrar carrito y lanzar pedido": "Chiudi il carrello e invia", "Cerrar pedido": "Chiudi ordine", "Total": "Totale", "HISTORIAL LOCAL": "CRONOLOGIA LOCALE", "En preparación": "In preparazione", "Cerrado": "Chiuso", "Todavía no lanzaste pedidos": "Non hai ancora inviato ordini",
    "Lomo de la casa": "Panino con bistecca della casa", "Papas para compartir": "Patatine da condividere", "Pizza de la casa": "Pizza della casa", "Gaseosa": "Bibita", "Lomo completo con papas, acompañado por una pinta artesanal.": "Panino con bistecca completo e patatine, accompagnato da una pinta artigianale.", "Papas especiadas y una cerveza dorada, una combinación bien cervecera.": "Patatine speziate e birra dorata, un perfetto abbinamento.", "Masa, salsa e ingredientes a confirmar con la carta oficial.": "Impasto, salsa e ingredienti da confermare con il menu ufficiale.", "Cerveza cobriza, maltosa y de cuerpo medio, con notas de caramelo y tostado.": "Birra ramata, maltata e di medio corpo, con note di caramello e tostato.", "Cerveza rubia ligera, refrescante y equilibrada, con perfil suave de malta y lúpulo.": "Birra bionda leggera, rinfrescante ed equilibrata, con un profilo delicato di malto e luppolo.", "Cerveza oscura y cremosa, con amargor moderado y notas tostadas de café y chocolate.": "Birra scura e cremosa, con amaro moderato e note tostate di caffè e cioccolato.", "Opciones y tamaños pendientes de confirmar con la carta oficial.": "Opzioni e formati da confermare con il menu ufficiale.", "Sabores y presentaciones pendientes de confirmar.": "Gusti e formati da confermare."
  },
  de: {
    "MENÚ GENERAL": "HAUPTMENÜ", "Mis pedidos": "Meine Bestellungen", "Preguntale al mozo": "Kellner fragen", "MENÚ DIGITAL · 23 RÍOS": "DIGITALE SPEISEKARTE · 23 RÍOS", "Elegí con los ojos.": "Wähle mit den Augen.", "Disfrutá a tu manera.": "Genieße es auf deine Art.", "Explorá nuestros productos con fotos reales o contanos qué te gusta y te ayudamos a encontrar la mejor combinación.": "Entdecke unsere Produkte mit echten Fotos oder sag uns, was du magst, und wir finden die beste Kombination.", "Ver la carta": "Speisekarte ansehen", "Quiero una recomendación": "Ich möchte eine Empfehlung", "Fotos reales": "Echte Fotos", "Sin imágenes genéricas": "Keine Stockbilder", "Cerveza propia": "Eigenes Bier", "De la fábrica a tu pinta": "Von der Brauerei ins Glas", "Elegí mejor": "Besser wählen", "Con ayuda cuando la necesites": "Hilfe, wenn du sie brauchst",
    "Llamar al mozo": "Kellner rufen", "Solicitar la cuenta": "Rechnung anfordern", "Pedido rápido": "Schnelle Anfrage", "Personalizable": "Anpassbar", "NUESTRA CARTA": "UNSERE SPEISEKARTE", "Algo para cada momento.": "Für jeden Moment das Richtige.", "Buscar en el menú": "Speisekarte durchsuchen", "Comida": "Essen", "Bebida": "Getränke", "Tipo de comida": "Speiseart", "Preferencias": "Vorlieben", "Evitar alérgenos": "Allergene vermeiden", "Tipo de bebida": "Getränkeart", "Estilo de cerveza": "Bierstil", "Papas fritas": "Pommes", "Lomos": "Steak-Sandwiches", "Pizzas": "Pizzen", "Vegetariano": "Vegetarisch", "Sin TACC": "Glutenfrei", "Para compartir": "Zum Teilen", "Gluten": "Gluten", "Lácteos": "Milchprodukte", "Huevo": "Ei", "Gaseosas": "Softdrinks", "Agua saborizada": "Aromatisiertes Wasser", "Cerveza": "Bier", "Rubia": "Hell", "Roja": "Rot", "Negra": "Dunkel", "Limpiar filtros": "Filter löschen", "resultado": "Ergebnis", "resultados": "Ergebnisse",
    "Tocá una foto para verla completa.": "Tippe auf ein Foto, um es vollständig zu sehen.", "Mostramos el producto real, en primer plano y sin sorpresas.": "Wir zeigen das echte Produkt aus der Nähe und ohne Überraschungen.", "Desde": "Ab", "Precio demo": "Beispielpreis", "Ver detalle": "Details ansehen", "Foto real pendiente": "Echtes Foto folgt", "FORMATO": "GRÖSSE", "¿Cómo la querés?": "Welche Größe möchtest du?", "Precios de muestra": "Beispielpreise", "Media pinta": "Halbes Pint", "Pinta": "Pint", "Jarra": "Krug",
    "INFORMACIÓN NUTRICIONAL": "NÄHRWERTANGABEN", "Valores nutricionales": "Nährwerte", "Calorías": "Kalorien", "Grasas": "Fett", "Proteínas": "Eiweiß", "Carbohidratos": "Kohlenhydrate", "Azúcares": "Zucker", "Alérgenos": "Allergene", "Información provisional": "Vorläufige Angaben", "Agregar al carrito": "In den Warenkorb", "Agregado al carrito": "Zum Warenkorb hinzugefügt", "Se puede acompañar con": "Passt gut zu",
    "CARRITO ABIERTO": "WARENKORB OFFEN", "PEDIDO LANZADO": "BESTELLUNG GESENDET", "Revisar carrito": "Warenkorb prüfen", "Ver estado del pedido": "Bestellstatus ansehen", "Revisá antes de lanzarlo": "Vor dem Senden prüfen", "Cerrar carrito y lanzar pedido": "Warenkorb schließen und bestellen", "Cerrar pedido": "Bestellung schließen", "Total": "Gesamt", "HISTORIAL LOCAL": "LOKALER VERLAUF", "En preparación": "In Zubereitung", "Cerrado": "Geschlossen", "Todavía no lanzaste pedidos": "Du hast noch keine Bestellungen gesendet",
    "Lomo de la casa": "Steak-Sandwich des Hauses", "Papas para compartir": "Pommes zum Teilen", "Pizza de la casa": "Pizza des Hauses", "Gaseosa": "Softdrink", "Lomo completo con papas, acompañado por una pinta artesanal.": "Belegtes Steak-Sandwich mit Pommes und einem Craft-Pint.", "Papas especiadas y una cerveza dorada, una combinación bien cervecera.": "Gewürzte Pommes und ein goldenes Bier – die perfekte Kombination.", "Masa, salsa e ingredientes a confirmar con la carta oficial.": "Teig, Sauce und Belag werden mit der offiziellen Speisekarte bestätigt.", "Cerveza cobriza, maltosa y de cuerpo medio, con notas de caramelo y tostado.": "Kupferfarbenes, malziges Bier mit mittlerem Körper sowie Karamell- und Röstaromen.", "Cerveza rubia ligera, refrescante y equilibrada, con perfil suave de malta y lúpulo.": "Leichtes, erfrischendes und ausgewogenes helles Bier mit sanftem Malz- und Hopfenprofil.", "Cerveza oscura y cremosa, con amargor moderado y notas tostadas de café y chocolate.": "Dunkles, cremiges Bier mit moderater Bitterkeit und Röstnoten von Kaffee und Schokolade.", "Opciones y tamaños pendientes de confirmar con la carta oficial.": "Optionen und Größen werden mit der offiziellen Speisekarte bestätigt.", "Sabores y presentaciones pendientes de confirmar.": "Geschmacksrichtungen und Größen werden noch bestätigt."
  }
};

const extras: Record<Exclude<Language, "es">, Record<string, string>> = {
  pt: {
    "MOZO DIGITAL": "GARÇOM DIGITAL", "Decime qué te gusta.": "Conte o que você gosta.", "Yo te ayudo a elegir.": "Eu ajudo você a escolher.", "Conversar ahora": "Conversar agora",
    "EVENTOS EN 23 RÍOS": "EVENTOS NO 23 RÍOS", "Siempre hay algo pasando.": "Sempre há algo acontecendo.", "Ferias, música, cultura y encuentros para disfrutar con una pinta en la mano.": "Feiras, música, cultura e encontros para curtir com uma cerveja na mão.", "Ver eventos": "Ver eventos", "AGENDA · 23 RÍOS": "AGENDA · 23 RÍOS", "Agenda de eventos": "Agenda de eventos", "Conocé lo que está pasando en 23 Ríos.": "Veja o que está acontecendo no 23 Ríos.", "Entrada libre y gratuita": "Entrada livre e gratuita", "Más eventos próximamente": "Mais eventos em breve", "La agenda está preparada para incorporar todas las fechas de cada mes.": "A agenda está pronta para incorporar todas as datas de cada mês.",
    "Menú digital general · Sin vinculación a mesa en esta etapa.": "Menu digital geral · Ainda sem vínculo com a mesa.", "El pedido todavía no fue lanzado.": "O pedido ainda não foi enviado.", "Podés seguir agregando productos o cerrar el carrito cuando esté completo.": "Você pode continuar adicionando produtos ou fechar o carrinho quando estiver completo.",
    "Pedido enviado correctamente": "Pedido enviado com sucesso", "Tu pedido está en marcha": "Seu pedido está em andamento", "PARA COMPLETAR TU ELECCIÓN": "PARA COMPLETAR SUA ESCOLHA", "Guardar para decidir después": "Salvar para decidir depois", "Guardado en favoritos": "Salvo nos favoritos", "Por porción": "Por porção", "Por 100 cc": "Por 100 cc", "Por botella de 500 cc": "Por garrafa de 500 cc", "producto": "produto", "productos": "produtos", "Información pendiente de validación con la carta oficial.": "Informação pendente de validação com o menu oficial.", "Los precios y valores nutricionales mostrados son demostrativos.": "Os preços e valores nutricionais exibidos são demonstrativos."
  },
  en: {
    "MOZO DIGITAL": "DIGITAL WAITER", "Decime qué te gusta.": "Tell me what you like.", "Yo te ayudo a elegir.": "I will help you choose.", "Conversar ahora": "Chat now",
    "EVENTOS EN 23 RÍOS": "EVENTS AT 23 RÍOS", "Siempre hay algo pasando.": "There is always something happening.", "Ferias, música, cultura y encuentros para disfrutar con una pinta en la mano.": "Fairs, music, culture and gatherings to enjoy with a pint in hand.", "Ver eventos": "View events", "AGENDA · 23 RÍOS": "CALENDAR · 23 RÍOS", "Agenda de eventos": "Events calendar", "Conocé lo que está pasando en 23 Ríos.": "See what is happening at 23 Ríos.", "Entrada libre y gratuita": "Free admission", "Más eventos próximamente": "More events coming soon", "La agenda está preparada para incorporar todas las fechas de cada mes.": "The calendar is ready to include every date each month.",
    "Menú digital general · Sin vinculación a mesa en esta etapa.": "General digital menu · Table connection is not enabled yet.", "El pedido todavía no fue lanzado.": "The order has not been sent yet.", "Podés seguir agregando productos o cerrar el carrito cuando esté completo.": "You can keep adding products or close the cart when it is complete.",
    "Pedido enviado correctamente": "Order sent successfully", "Tu pedido está en marcha": "Your order is in progress", "PARA COMPLETAR TU ELECCIÓN": "COMPLETE YOUR SELECTION", "Guardar para decidir después": "Save for later", "Guardado en favoritos": "Saved to favorites", "Por porción": "Per serving", "Por 100 cc": "Per 100 cc", "Por botella de 500 cc": "Per 500 cc bottle", "producto": "item", "productos": "items", "Información pendiente de validación con la carta oficial.": "Information pending validation with the official menu.", "Los precios y valores nutricionales mostrados son demostrativos.": "The prices and nutrition values shown are for demonstration purposes."
  },
  fr: {
    "MOZO DIGITAL": "SERVEUR NUMÉRIQUE", "Decime qué te gusta.": "Dites-moi ce que vous aimez.", "Yo te ayudo a elegir.": "Je vous aide à choisir.", "Conversar ahora": "Discuter maintenant",
    "EVENTOS EN 23 RÍOS": "ÉVÉNEMENTS CHEZ 23 RÍOS", "Siempre hay algo pasando.": "Il se passe toujours quelque chose.", "Ferias, música, cultura y encuentros para disfrutar con una pinta en la mano.": "Marchés, musique, culture et rencontres à savourer une bière à la main.", "Ver eventos": "Voir les événements", "AGENDA · 23 RÍOS": "AGENDA · 23 RÍOS", "Agenda de eventos": "Agenda des événements", "Conocé lo que está pasando en 23 Ríos.": "Découvrez ce qui se passe chez 23 Ríos.", "Entrada libre y gratuita": "Entrée libre et gratuite", "Más eventos próximamente": "D'autres événements bientôt", "La agenda está preparada para incorporar todas las fechas de cada mes.": "L'agenda est prêt à accueillir toutes les dates de chaque mois.",
    "Menú digital general · Sin vinculación a mesa en esta etapa.": "Menu numérique général · Connexion à la table non activée.", "El pedido todavía no fue lanzado.": "La commande n'a pas encore été envoyée.", "Podés seguir agregando productos o cerrar el carrito cuando esté completo.": "Vous pouvez continuer à ajouter des produits ou fermer le panier lorsqu'il est complet.",
    "Pedido enviado correctamente": "Commande envoyée avec succès", "Tu pedido está en marcha": "Votre commande est en cours", "PARA COMPLETAR TU ELECCIÓN": "POUR COMPLÉTER VOTRE CHOIX", "Guardar para decidir después": "Enregistrer pour plus tard", "Guardado en favoritos": "Enregistré dans les favoris", "Por porción": "Par portion", "Por 100 cc": "Pour 100 cc", "Por botella de 500 cc": "Par bouteille de 500 cc", "producto": "produit", "productos": "produits", "Información pendiente de validación con la carta oficial.": "Informations en attente de validation avec le menu officiel.", "Los precios y valores nutricionales mostrados son demostrativos.": "Les prix et valeurs nutritionnelles affichés sont indicatifs."
  },
  it: {
    "MOZO DIGITAL": "CAMERIERE DIGITALE", "Decime qué te gusta.": "Dimmi cosa ti piace.", "Yo te ayudo a elegir.": "Ti aiuto a scegliere.", "Conversar ahora": "Parla ora",
    "EVENTOS EN 23 RÍOS": "EVENTI AL 23 RÍOS", "Siempre hay algo pasando.": "C'è sempre qualcosa in programma.", "Ferias, música, cultura y encuentros para disfrutar con una pinta en la mano.": "Fiere, musica, cultura e incontri da vivere con una birra in mano.", "Ver eventos": "Vedi eventi", "AGENDA · 23 RÍOS": "AGENDA · 23 RÍOS", "Agenda de eventos": "Agenda eventi", "Conocé lo que está pasando en 23 Ríos.": "Scopri cosa succede al 23 Ríos.", "Entrada libre y gratuita": "Ingresso libero e gratuito", "Más eventos próximamente": "Altri eventi in arrivo", "La agenda está preparada para incorporar todas las fechas de cada mes.": "L'agenda è pronta a includere tutte le date di ogni mese.",
    "Menú digital general · Sin vinculación a mesa en esta etapa.": "Menu digitale generale · Collegamento al tavolo non ancora attivo.", "El pedido todavía no fue lanzado.": "L'ordine non è ancora stato inviato.", "Podés seguir agregando productos o cerrar el carrito cuando esté completo.": "Puoi continuare ad aggiungere prodotti o chiudere il carrello quando è completo.",
    "Pedido enviado correctamente": "Ordine inviato correttamente", "Tu pedido está en marcha": "Il tuo ordine è in corso", "PARA COMPLETAR TU ELECCIÓN": "PER COMPLETARE LA TUA SCELTA", "Guardar para decidir después": "Salva per dopo", "Guardado en favoritos": "Salvato nei preferiti", "Por porción": "Per porzione", "Por 100 cc": "Per 100 cc", "Por botella de 500 cc": "Per bottiglia da 500 cc", "producto": "prodotto", "productos": "prodotti", "Información pendiente de validación con la carta oficial.": "Informazioni in attesa di convalida con il menu ufficiale.", "Los precios y valores nutricionales mostrados son demostrativos.": "I prezzi e i valori nutrizionali mostrati sono dimostrativi."
  },
  de: {
    "MOZO DIGITAL": "DIGITALER KELLNER", "Decime qué te gusta.": "Sag mir, was du magst.", "Yo te ayudo a elegir.": "Ich helfe dir bei der Auswahl.", "Conversar ahora": "Jetzt chatten",
    "EVENTOS EN 23 RÍOS": "EVENTS IM 23 RÍOS", "Siempre hay algo pasando.": "Hier ist immer etwas los.", "Ferias, música, cultura y encuentros para disfrutar con una pinta en la mano.": "Märkte, Musik, Kultur und Begegnungen – am besten mit einem Bier in der Hand.", "Ver eventos": "Events ansehen", "AGENDA · 23 RÍOS": "KALENDER · 23 RÍOS", "Agenda de eventos": "Veranstaltungskalender", "Conocé lo que está pasando en 23 Ríos.": "Entdecke, was im 23 Ríos passiert.", "Entrada libre y gratuita": "Eintritt frei", "Más eventos próximamente": "Weitere Events folgen", "La agenda está preparada para incorporar todas las fechas de cada mes.": "Der Kalender ist bereit für alle Termine des Monats.",
    "Menú digital general · Sin vinculación a mesa en esta etapa.": "Allgemeine digitale Speisekarte · Noch keine Tischverknüpfung.", "El pedido todavía no fue lanzado.": "Die Bestellung wurde noch nicht gesendet.", "Podés seguir agregando productos o cerrar el carrito cuando esté completo.": "Du kannst weitere Produkte hinzufügen oder den Warenkorb schließen, wenn er vollständig ist.",
    "Pedido enviado correctamente": "Bestellung erfolgreich gesendet", "Tu pedido está en marcha": "Deine Bestellung wird bearbeitet", "PARA COMPLETAR TU ELECCIÓN": "DEINE AUSWAHL ERGÄNZEN", "Guardar para decidir después": "Für später speichern", "Guardado en favoritos": "In Favoriten gespeichert", "Por porción": "Pro Portion", "Por 100 cc": "Pro 100 cc", "Por botella de 500 cc": "Pro 500-cc-Flasche", "producto": "Produkt", "productos": "Produkte", "Información pendiente de validación con la carta oficial.": "Informationen müssen noch mit der offiziellen Speisekarte bestätigt werden.", "Los precios y valores nutricionales mostrados son demostrativos.": "Die angezeigten Preise und Nährwerte dienen nur zur Demonstration."
  }
};

export function translate(language: Language, text: string) {
  if (language === "es") return text;
  return dictionaries[language][text] ?? extras[language][text] ?? text;
}
